[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 1000
via_ir = true
gas_limit = 30000000
gas_price = 100000000
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

# Sei Network Configuration
[rpc_endpoints]
sei-testnet = "https://evm-rpc-testnet.sei-apis.com"
sei-mainnet = "https://evm-rpc.sei-apis.com"

[etherscan]
sei-testnet = { key = "${SEI_ETHERSCAN_API_KEY}", url = "https://seitrace.com/api" }

# Testing configuration
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 500